networks:
  app-tier:
    driver: bridge

services:
  etcd:
    image: 'bitnami/etcd:latest'
    container_name: etcd
    restart: always
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - app-tier
  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    restart: always
    user: root
    environment:
      - REDIS_PASSWORD=noy
      # - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
    volumes:
      - '.dbdata/redis:/bitnami/redis'
    networks:
      - app-tier
  server-1:
    image: 'noy/echoserver:latest'
    container_name: server-1
    restart: always
    ports:
      - 18080:8080
      - 19090:9090
    volumes:
      - './yapr.yaml:/app/yapr.yaml'
      - './.logs:/.logs'
    command: ./yapr_echo_server --name=svr1 --ip=server-1 --weight=1
    depends_on:
      - etcd
      - redis
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - app-tier
  server-2:
    image: 'noy/echoserver:latest'
    container_name: server-2
    restart: always
    ports:
      - 18081:8080
      - 19091:9090
    expose:
      - "23333-27333:23333-27333"
    volumes:
      - './yapr.yaml:/app/yapr.yaml'
      - './.logs:/.logs'
    command: ./yapr_echo_server --name=svr2 --ip=server-2 --weight=2 --gracefulStop=false
    depends_on:
      - etcd
      - redis
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - app-tier
  server-3:
    image: 'noy/echoserver:latest'
    container_name: server-3
    restart: always
    ports:
      - 18082:8080
      - 19092:9090
    expose:
      - "23333-27333:23333-27333"
    volumes:
      - './yapr.yaml:/app/yapr.yaml'
      - './.logs:/.logs'
    command: ./yapr_echo_server --name=svr3 --ip=server-3 --weight=3
    depends_on:
      - etcd
      - redis
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - app-tier
  client-1:
    image: 'noy/echoclient:latest'
    container_name: client-1
    restart: always
    ports:
      - 18090:8080
      - 19080:9090
    expose:
      - "23333-27333:23333-27333"
    volumes:
      - './yapr.yaml:/app/yapr.yaml'
      - './shard.lua:/app/shard.lua'
      - './.logs:/.logs'
    command: ./yapr_echo_client --name=cli1
    depends_on:
      - etcd
      - redis
      - server-1
      - server-2
      - server-3
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - app-tier
  client-2:
    image: 'noy/echoclient:latest'
    container_name: client-2
    restart: always
    ports:
      - 18091:8080
      - 19081:9090
    volumes:
      - './yapr.yaml:/app/yapr.yaml'
      - './shard.lua:/app/shard.lua'
      - './.logs:/.logs'
    command: ./yapr_echo_client --name=cli2
    depends_on:
      - etcd
      - redis
      - server-1
      - server-2
      - server-3
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - app-tier
  # ---------- monitor ----------
  prometheus:
    image: 'prom/prometheus'
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
    networks:
      - app-tier
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    user: '0'
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./grafana-conf:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    networks:
      - app-tier
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: always
    ports:
      - "9100:9100"
    networks:
      - app-tier
  redis-exporter:
    image: oliver006/redis_exporter
    container_name: redis-exporter
    restart: always
    ports:
      - "9121:9121"
    command:
      - '--redis.addr=redis://:noy@redis:6379'
    networks:
      - app-tier