networks:
  app-tier:
    driver: bridge

services:
  etcd:
    image: 'bitnami/etcd:latest'
    container_name: etcd
    restart: always
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - app-tier
  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    restart: always
    user: root
    environment:
      - REDIS_PASSWORD=noy
      # - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
    volumes:
      - '.dbdata/redis:/bitnami/redis'
    networks:
      - app-tier
  # ---------- monitor ----------
  prometheus:
    image: 'prom/prometheus'
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
    networks:
      - app-tier
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    user: '0'
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./grafana-conf:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    networks:
      - app-tier
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: always
    ports:
      - "9100:9100"
    networks:
      - app-tier
  redis-exporter:
    image: oliver006/redis_exporter
    container_name: redis-exporter
    restart: always
    ports:
      - "9121:9121"
    command:
      - '--redis.addr=redis://:noy@redis:6379'
    networks:
      - app-tier