global:
  scrape_interval:     1s
  evaluation_interval: 1s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']
  - job_name: 'node'
    static_configs:
    - targets: ['node-exporter:9100']
  - job_name: 'redis'
    static_configs:
    - targets: ['redis-exporter:9121']
  - job_name: 'client'
    static_configs:
    - targets: ['client-1:8080','client-2:8080','localhost:8080']
  - job_name: 'server'
    static_configs:
    - targets: ['server-1:8080','server-2:8080','server-3:8080','localhost:8081']