global:
  scrape_interval:     1s
  evaluation_interval: 1s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']
  - job_name: 'node'
    static_configs:
    - targets: ['node-exporter:9100']
  - job_name: 'redis'
    static_configs:
    - targets: ['redis-exporter:9121']
#  - job_name: 'scheduler'
#    static_configs:
#    - targets: ['scheduler-1:8080','scheduler-2:8080']
#  - job_name: 'worker'
#    static_configs:
#    - targets: ['worker-1:8080','worker-2:8080']