# etcd 集群配置
etcd:
  endpoints:
    - etcd:2379
  dialTimeout: 5s
  username: ""
  password: ""

# redis 集群配置
redis:
  url: "redis://:noy@redis:6379"

# yapr 配置
yapr:
  # 版本号增加时会更新数据库
  version: 1.0
  routers:
    - name: "echo"
      rules:
        - priority: 0
          matchers:
            - uri: ".*/Echo"
              port: 9090
          selector: "echo-dir"
        - priority: 1
          matchers:
            - uri: ".*/Echo"
              port: 9090
          selector: "echo-rr"
  selectors:
    - name: "echo-dir"
      service: "echosvr"
      port: 9090
      key: "x-uid"
      strategy: "direct"
    - name: "echo-rr"
      service: "echosvr"
      port: 9090
      key: "x-uid"
      strategy: "round_robin"