# etcd 集群配置
etcd:
  endpoints:
    - etcd:2379
  dialTimeout: 5s
  username: ""
  password: ""

# redis 集群配置
redis:
  url: "redis://:noy@redis:6379"

# yapr 配置
yapr:
  routers:
    - name: "echo"
      rules:
        - priority: 1
          matchers:
            - uri: ".*/Echo"
              port: 9090
          selector: "s1"
  selectors:
    - name: "s1"
      service: "echosvr"
      port: 9090
      strategy: "weighted_round_robin"