# etcd 集群配置
etcd:
  endpoints:
    - etcd:2379
  dialTimeout: 5s
  username: ""
  password: ""

# redis 集群配置
redis:
  url: "redis://:noy@redis:6379"

# yapr 配置
yapr:
  # 版本号增加时会更新数据库
  version: 1.0
  routers:
    - name: "echo"
      rules:
        - matchers:
            - uri: ".*/Echo"
              port: 9090
          selector: "echo-dir"
          error_handler:
            no_endpoint: "pass"
            bad_endpoint: "block"

        - matchers:
            - uri: ".*/Echo"
              port: 9090
          selector: "shard"

  selectors:
    - name: "echo-dir"
      service: "echosvr"
      port: 9090
      key: "x-uid"
      strategy: "direct"
      cache_size: 3
      cache_type: "lru"

    - name: "echo-rr"
      service: "echosvr"
      port: 9090
      strategy: "round_robin"

    - name: "shard"
      service: "echosvr"
      port: 9090
      strategy: "custom"
      script : "/app/shard.lua"